<%@ Page Language="C#" MasterPageFile="~/Teacher/Teacher.master" AutoEventWireup="true" CodeFile="View Reports.aspx.cs" Inherits="Admin_View_Reports" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table align="center" cellpadding="0" cellspacing="5" class="border1" width="600">
        <tr>
            <td align="center" class="border" colspan="5" style="height: 23px">
                <b class="title">View Reports Details</b>
            </td>
        </tr>
        <tr>
            <td align="center"> <strong>Select Class: </strong>
               </td>
               <td style="width: 278px">
                   <asp:DropDownList ID="DDLClass" runat="server" AppendDataBoundItems="True" AutoPostBack="True"
                       OnSelectedIndexChanged="DDLClass_SelectedIndexChanged" Width="152px">
                       <asp:ListItem>Select....</asp:ListItem>
                   </asp:DropDownList></td>
               <td><strong>Select Student:</strong></td>
               <td>
                   <asp:DropDownList ID="DDLStudent" runat="server" AppendDataBoundItems="True" Width="151px" OnSelectedIndexChanged="DDLStudent_SelectedIndexChanged" AutoPostBack="True">
                       <asp:ListItem>Select...</asp:ListItem>
                   </asp:DropDownList></td>
        </tr>
        <tr>
            <td align="center">
            </td>
            <td align="right" style="width: 278px">
                <asp:Label ID="LblMsg" runat="server" Text="Label"></asp:Label></td>
            <td>
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td align="center" colspan="5">
                <asp:GridView ID="GdVReports" runat="server" AutoGenerateColumns="False"
                    AutoGenerateDeleteButton="True" CssClass="gridalter" 
                    OnRowCommand="GdVClass_RowCommand" OnRowDeleting="GdVClass_RowDeleting"
                    >
                    <Columns>
                        <asp:TemplateField>
                            <ItemTemplate>
                                <asp:LinkButton ID="LinkButton1" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"MarksID") %>'
                                    CommandName="Edit">Edit</asp:LinkButton>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="MarksID" HeaderText="MarksID" />
                        <asp:BoundField DataField="Class" HeaderText="Class" />
                        <asp:BoundField DataField="Subjects" HeaderText="Subjects" />
                        <asp:BoundField DataField="StudentName" HeaderText="StudentName" />
                        <asp:BoundField DataField="TypeOfExam" HeaderText="Type Of Exam" />
                        <asp:BoundField DataField="Marks" HeaderText="Marks" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

