<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true"
    CodeFile="View Teachers.aspx.cs" Inherits="Admin_View_Teachers" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table cellspacing="5" cellpadding="0" align="center" width="600" class="border1">
        <tr>
            <td class="border" colspan="2" align="center">
                <b class="title">View Teacher Details</b>
            </td>
        </tr>
        <tr>
            <td align="center">
                <asp:Label ID="Label1" runat="server" Style="position: static" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td align="center" style="height: 313px">
               <asp:Panel ID="Panel1" runat="server" Height="380px" Width="600px" ScrollBars="Auto">
                    <asp:GridView ID="GridView1" runat="server" Style="position: static" AutoGenerateColumns="False"
                        CssClass="gridalter" AutoGenerateDeleteButton="True" OnRowDeleting="GridView1_RowDeleting"
                        OnRowCommand="GridView1_RowCommand">
                        <Columns>
                            <asp:TemplateField>
                                <ItemTemplate>
                                    <asp:LinkButton ID="LinkButton1" runat="server" CommandName="Edit" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"TeacherID") %>'>Edit</asp:LinkButton>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:BoundField DataField="TeacherID" HeaderText="TeacherID" />
                            <asp:BoundField DataField="FullName" HeaderText="FullName" />
                            <asp:BoundField DataField="ClassTeacher" HeaderText="Subject" />
                            <asp:BoundField DataField="DateofBirth" HeaderText="DateofBirth" />
                            <asp:BoundField DataField="Email" HeaderText="Email" />
                            <asp:BoundField DataField="Address" HeaderText="Address" />
                            <asp:BoundField DataField="Area" HeaderText="Area" />
                            <asp:BoundField DataField="City" HeaderText="City" />
                            <asp:BoundField DataField="State" HeaderText="State" />
                            <asp:BoundField DataField="Country" HeaderText="Country" />
                            <asp:BoundField DataField="PhoneNo" HeaderText="PhoneNo" />
                        </Columns>
                    </asp:GridView>
                </asp:Panel>
            </td>
        </tr>
    </table>
</asp:Content>
