<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="View Assignment.aspx.cs" Inherits="View_Assignment" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<script language="javascript" type="text/javascript">
  function check()
   {
            var DDLClass=document.getElementById("<%=DDLClass.ClientID%>").selectedIndex;
            if(DDLClass==0)
            {
                alert('Class Required');
                return false;
            }
           
         
             var DDLSubject=document.getElementById("<%=DDLSubject.ClientID%>").selectedIndex;
            if(DDLSubject==0)
            {
                alert('Subject Required');
                return false;
            }
            
          
   }
   </script>
     <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="600">
        <tr>
            <td align="center" class="border" colspan="4">
                <b class="title">View Assignment</b></td>
        </tr>
        <tr>
            <td align="right" ><font color="red">*</font><span><b> Please Select Class:</b></span>
               </td>
            <td style="width: 221px" >
                <asp:DropDownList ID="DDLClass" runat="server" Width="95px" AppendDataBoundItems="True" AutoPostBack="True" OnSelectedIndexChanged="DDLClass_SelectedIndexChanged">
                    <asp:ListItem>Select...</asp:ListItem>
                </asp:DropDownList>
                &nbsp; &nbsp;&nbsp;
            </td>
            <td align="right"><font color="red">*</font><span><b> Please Select Subject:</b></span>
            </td>
            <td >
                <asp:DropDownList ID="DDLSubject" runat="server" Width="95px" AppendDataBoundItems="True" AutoPostBack="True" OnSelectedIndexChanged="DDLSubject_SelectedIndexChanged" >
                    <asp:ListItem>Select...</asp:ListItem>
                </asp:DropDownList></td>
        </tr>
        <tr>
            <td colspan="4" align="center">
                <asp:Label ID="LblMsg" runat="server"></asp:Label></td>
        </tr>
        <tr>
            <td colspan="4" align="center">
                <asp:GridView ID="GdVAssignment" runat="server" AutoGenerateColumns="False" 
                    AutoGenerateDeleteButton="True" AllowPaging="True" 
                    OnPageIndexChanging="GdVAssignment_PageIndexChanging" 
                    OnRowCommand="GdVAssignment_RowCommand" PageSize="8" CssClass="gridalter" 
                    OnRowDeleting="GdVAssignment_RowDeleting" CellPadding="4" ForeColor="#333333" 
                    GridLines="None">
                    <RowStyle BackColor="#E3EAEB" />
                    <Columns>
                        <asp:BoundField DataField="AsignmentsID" HeaderText="ID" />
                        <asp:BoundField DataField="Subject" HeaderText="Subject" />
                        <asp:BoundField DataField="NameOFasgmt" HeaderText="Name" />
                        <asp:BoundField DataField="SubmissionDate" HeaderText="SubmissionDate" />
                       <asp:HyperLinkField DataNavigateUrlFields="FilePath" DataNavigateUrlFormatString="Images/{0}"
                    DataTextField="FilePath" HeaderText="File" Target="_blank" >
                           <ControlStyle ForeColor="Navy" />
                       </asp:HyperLinkField>
                    </Columns>
                    <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
                    <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
                    <HeaderStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
                    <EditRowStyle BackColor="#7C6F57" />
                    <AlternatingRowStyle BackColor="White" />
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

