<%@ Page Language="C#" MasterPageFile="~/Admin/AdminMasterPage.master" AutoEventWireup="true" CodeFile="ViewHolidays .aspx.cs" Inherits="ViewHolidays_" Title="Untitled Page" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table align="center" cellpadding="0" cellspacing="5" class="border1" style="position: static"
        width="700">
        <tr>
            <td align="center" class="border" colspan="3">
                <b class="title">List of &nbsp;Holidays</b></td>
        </tr>
        <tr>
            <td colspan="3" align="center" >
                <asp:Label ID="Label1" runat="server" Text="Label"></asp:Label></td>
        </tr>
        <tr>
            <td colspan="3" align="center" >
                <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AllowPaging="True" OnPageIndexChanging="GridView1_PageIndexChanging" OnRowCommand="GridView1_RowCommand" OnRowDeleting="GridView1_RowDeleting" AutoGenerateColumns="False" CssClass="gridalter" Width="475px">
                    <Columns>
                        <asp:TemplateField>
                        <ItemTemplate>
                          <asp:LinkButton ID="LinkButton1" runat="server" CommandArgument='<%#DataBinder.Eval(Container.DataItem,"HolidayID") %>'
                                    CommandName="Edit">Edit</asp:LinkButton>
                        </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="HolidayID" HeaderText="HolidayID" />
                        <asp:BoundField DataField="Title" HeaderText="Event" />
                        <asp:BoundField DataField="HolidayDate" HeaderText="HolidayDate" />
                    </Columns>
                </asp:GridView>
            </td>
        </tr>
    </table>
</asp:Content>

